package main

import (
	"Omiran-App/backend/handler"
	"Omiran-App/backend/redis"
	"time"

	"Omiran-App/backend/dbutils"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/swaggo/gin-swagger/example/basic/docs" // docs is generated by Swag CLI, you have to import it.
)

func init() {
	dbutils.Open("config.yaml")
	handler.InitGQLSchema()
	redis.InitCache()
}

func main() {
	// os.Setenv("PORT", "9090")
	r := gin.Default()
	r.Use(cors.New(cors.Config{
		AllowOrigins:     []string{"http://localhost:3000"},
		AllowMethods:     []string{"POST", "GET", "PUT", "PATCH", "OPTIONS", "DELETE"},
		AllowHeaders:     []string{"Origin"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
		AllowOriginFunc: func(origin string) bool {
			return origin == "https://github.com"
		},
		MaxAge: 12 * time.Hour,
	}))
	// r.Use(cors.Default())
	url := ginSwagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))
	r.POST("/graphql", handler.GraphQLService)
	r.POST("/signup", handler.AccountCreationHandler)
	r.POST("/auth", handler.AuthHandler)
	// r.POST("/follow", handler.StartFollowingHandler)
	r.POST("/refresh", handler.RefreshSessionHandler)
	r.POST("/signin", handler.SignInHandler)
	r.DELETE("/signout", handler.SignOut)
	r.POST("/follow", handler.CreateFollowsHandler)
	r.DELETE("/unfollow", handler.DeleteFollowsHandler)
	// Streaming related routes
	r.POST("/streamauth", handler.StartStreamAuth)
	r.GET("/getstreamkey", handler.GetStreamKey)
	r.GET("/newstreamkey", handler.CreateNewStreamKey)
	r.Run()
}
