name: test

on:
    push:
        branches:
           - master 

jobs:
    test:
        runs-on: ubuntu-18.04
        steps:
            - name: backend-runtime-check
              run: go run backend/main.go